version: '3'
services:
  eureka-server:
    image: discovery-server-v1-cc
    container_name: discovery-server-cc
    build:
      context: ./discovery-server
      dockerfile: deploy/Dockerfile
    ports:
      - "8761:8761"

  config-server:
    image: config-server-v1-cc
    container_name: config-server-cc
    build:
      context: ./config-server
      dockerfile: deploy/Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      spring.profiles.active: git
    links:
      - eureka-server:eureka-server

  client-config-first:
    image: client-config-first-v1-cc
    container_name: client-config-first
    build:
      context: ./client-config-first
      dockerfile: deploy/Dockerfile
    ports:
      - "8763:8763"
    depends_on:
      - eureka-server
      - config-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      CONFIG_URI: http://config-server:8888
    links:
      - eureka-server:eureka-server
      - config-server:config-server
  client-discovery-first:
    image: client-discovery-first-v1-cc
    container_name: client-discovery-first
    build:
      context: ./client-discovery-first
      dockerfile: deploy/Dockerfile
    ports:
      - "8764:8764"
    depends_on:
      - eureka-server
      - config-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
    links:
      - eureka-server:eureka-server
      - config-server:config-server