server:
  port: 8761

eureka:
  instance:
    appname: ${spring.application.name}
    virtual-host-name: ${spring.application.name}
    ip-address: ${spring.cloud.client.ip-address}
    hostname: ${spring.cloud.client.ip-address}
    non-secure-port: 8761
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
    registry-fetch-interval-seconds: 5
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.49
    wait-time-in-ms-when-sync-empty: 10000
    peer-node-connect-timeout-ms: 5000
    peer-node-total-connections: 1000
    eviction-interval-timer-in-ms: 2000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
endpoints:
  health.sensive: flase

spring:
  application:
    name: discovery-server
  profiles:
    active: local