server:
  port: 8766
spring:
  profiles:
    active: gcp
  cloud:
    config:
      override-system-properties: false
  zipkin:
    base-url: http://ppe-zipkin-server/
  sleuth:
    sampler:
      rate: 1.0


feign:
  hystrix:
    enabled: true