server:
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: git
  application:
    name: ppe-config-server
  cloud:
    config:
      override-system-properties: false
      server:
        git:
          uri: https://github.com/prasanna29387/ppe.git
          clone-on-start: true
          search-paths:
            ppe-config-server/src/main/resources/config/,
            ppe-config-server/src/main/resources/config/ppe-admin-server/,
            ppe-config-server/src/main/resources/config/ppe-email-service/,
            ppe-config-server/src/main/resources/config/ppe-payroll-service/,
            ppe-config-server/src/main/resources/config/ppe-orchestration-service/,
            ppe-config-server/src/main/resources/config/ppe-backup-service/,
            ppe-config-server/src/main/resources/config/ppe-data-store
          username: prasanna29387
          password: Yamu2429$
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true