server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: git
  application:
    name: config-server
  cloud:
    config:
      override-system-properties: false
      server:
        git:
          uri: https://github.com/athulravindran87/spring-cloud-config.git
          clone-on-start: true
          search-paths:
            config-server/src/main/resources/config/,
            config-server/src/main/resources/config/client-config-first,
            config-server/src/main/resources/config/client-discovery-first
          username: prasanna29387
          password: Yamu2429$
    bus:
      enabled: true
    kafka:
      bootstrap-servers: http://192.168.1.247:9092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true