server:
  port: 8767
spring:
  profiles:
    active: gcp
  cloud:
    config:
      override-system-properties: false
  zipkin:
    base-url: http://ppe-zipkin-server/
  sleuth:
    sampler:
      rate: 1.0

clients:
  name: immanuel_agencies,saisri_lables,Client Original