server:
  port: 8765
spring:
  profiles:
    active: gcp
  cloud:
    config:
      override-system-properties: false
  zipkin:
    base-url: http://ppe-zipkin-server/
  sleuth:
    sampler:
      rate: 1.0

ufs_kone:
  name: UNITED FACILITIES SERVICES
  address: Old No.20/New No.2, First Floor,\n\t2nd Cross Street,Indira Nagar, Adyar,\n\tChennai, Tamil Nadu 600020, India \n 22546500
  pmrpy: N
  earnings: format1

immanuel_agencies:
  name: IMMANUEL AGENCIES
  address: 11 Jawaharlal Street, New Perungalathur\n\tSrinivasa Nagar ,Chennai 600 063\n\tMobile No - 98400 48727
  pmrpy: N
  earnings: format2

saisri_lables:
  name: SAI SRI LABELS INDIA PVT LTD
  address: Plot No:B-32(B), SIDCO Industrial Estate,\n\tMaraimalai nagar, Kancheepuram District, Tamil Nadu - 603209
  pmrpy: Y
  earnings: format3